# Generated by Django 4.0.1 on 2022-02-26 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_alter_folhames_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proventosmes',
            name='folhames',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.folhames'),
        ),
        migrations.AlterField(
            model_name='proventosmes',
            name='provdesc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.provdesc'),
        ),
    ]
